--- # Jenkins Main Playbook

- hosts: localhost
  connection: local
  become: yes
  tasks:

  - name: execute PreSetup Playbook
    include_tasks: preSetup.yml

  - name: execute installJenkins Playbook
    include_tasks: installJenkins.yml
    tags: installjenkins

  handlers:

    - name: restart docker
      service:
        name: docker
        state: restarted
